### ISSUE TITLE
Argument of type 'Buffer' is not assignable to parameter of type 'InputSchema | undefined'.

### ISSUE THREAD

**Issue by TJ-Stamp** [marcomaroni-github/instagram-to-bluesky#3]
Not able to run this currently... with a freshly downloaded and unzipped archive the tool fails to run providing this error:

```
npm run start_log

> instagramtobluesky@0.1.0 start_log
> npx tsc && node app.js > import.log

app.ts:151:63 - error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'InputSchema | undefined'.
  Type 'Buffer' is not assignable to type 'Uint8Array'.
    The types returned by 'entries()' are incompatible between these types.
      Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 9 more.

151                     const blobRecord = await agent.uploadBlob(imageBuffer, {
                                                                  ~~~~~~~~~~~


Found 1 error in app.ts:151
```

.env file looks right:

BLUESKY_USERNAME = *****
BLUESKY_PASSWORD = *****
ARCHIVE_FOLDER = /nas/nvme/tempo/instagram
SIMULATE = 1

validated the archive folder is correct:

ls -l /nas/nvme/tempo/instagram
total 36
drwxrwxr-x 2 root root     0 Nov 21 08:34 ads_information
drwxrwxr-x 2 root root     0 Nov 21 08:34 apps_and_websites_off_of_instagram
drwxrwxr-x 2 root root     0 Nov 21 08:34 connections
drwxrwxr-x 2 root root     0 Nov 21 08:34 files
drwxrwxr-x 2 root root     0 Nov 21 08:34 logged_information
drwxrwxr-x 2 root root     0 Nov 21 08:34 media
drwxrwxr-x 2 root root     0 Nov 21 08:34 personal_information
drwxrwxr-x 2 root root     0 Nov 21 08:35 preferences
drwxrwxr-x 2 root root     0 Nov 21 08:35 security_and_login_information
-rwxrwxr-x 1 root root 35979 Nov 21 08:31 start_here.html
drwxrwxr-x 2 root root     0 Nov 21 08:35 your_instagram_activity

**Comment by marcomaroni-github** [comment]
Try the new release v.0.1.2 and run `npm i` again and let me know...

**Comment by TJ-Stamp** [comment]
Thanks! this did the trick... I did one hurdle.

The readme doesn't specify the archive format to generate and download from the instagram accounts center so I used the html one, which caused this error:

`npm run start_log

> instagramtobluesky@0.1.2 start_log
> npx tsc && node app.js > import.log

node:fs:561
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open '/nas/nvme/tempo/instagram/your_instagram_activity/content/posts_1.json'
    at Object.openSync (node:fs:561:18)
    at Object.readFileSync (node:fs:445:35)
    at main (/home/*****/instagram-to-bluesky-main/app.js:66:38)
    at Object.<anonymous> (/home/*****/instagram-to-bluesky-main/app.js:205:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/nas/nvme/tempo/instagram/your_instagram_activity/content/posts_1.json'
}

Node.js v22.11.0
`

I checked the archive folder and spotted /nas/nvme/tempo/instagram/your_instagram_activity/content/posts_1.html existed rather than the .json it was looking for.

Once I re-requested the archive in JSON format and tried that instead the tool worked perfectly :)
